version: '3.5'

name: potz

services:
  traefik:
    image: 'traefik:latest'
    container_name: traefik
    hostname: traefik
    command:
      # Docker
      - '--providers.docker.swarmMode=false'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=main'
      # Configure entrypoints
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      # HTTPS
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.letsencrypt.acme.email=jens@jenspots.com'
      - '--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json'
      # Global HTTP -> HTTPS
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      # Enable dashboard
      - '--api.dashboard=false'
      # Set log level
      # - '--log.level=DEBUG'
    ports:
      - '443:443'
      - '80:80'
      # - "8080:8080"
    networks:
      main:
    volumes:
      - '~/volumes/traefik:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  potz:
    container_name: potz
    hostname: potz
    build:
      dockerfile: ./Dockerfile
      context: .
      target: 'production'
    networks:
      main:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.potz.rule=Host(`potz.be`,`www.potz.be`)'
      - 'traefik.http.routers.potz.entrypoints=websecure'
      - 'traefik.http.routers.potz.tls.certresolver=letsencrypt'
      - 'traefik.http.services.potz.loadbalancer.server.port=3000'
    restart: always

networks:
  main:
    name: main
